application: crowdocracy-1312
version: 0-99

runtime: python27
api_version: 1
threadsafe: false


handlers:
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /static/
  static_dir: static

- url: /.*
  script: main.py


libraries:
- name: pycrypto
  version: latest
